### ISSUE TITLE
What's the intended behavior for the code below from the DAO?

### ISSUE THREAD

**Issue by saoj** [klutzer/restapp#3]
```
   public DummyBean get(DummyBean proto) {

        try {
            if (!session.load(proto)) {
                return null;
            }

            return proto;

        }catch (BeanException e) {

            return session.loadUnique(proto);
        }
    }
```

What happens to `load` if the bean does not have a primary key? This might swallow an exception if the PK is not the problem, no?

**Comment by klutzer** [comment]
The ideia here is simply to "join" the load and loadUnique functionalities. If the user gives a bean with PK, the load is executed, otherwise it tries to load by properties (loadUnique)..

But you're right, if session.load throws an exception, it will never be caught..

**Comment by klutzer** [comment]
Solved: Now AbstractDAO has two methods `getById()` and `getByExample()`
