### ISSUE TITLE
Perhaps make ConnectionManager implement Factory from MentaContainer?

### ISSUE THREAD

**Issue by saoj** [klutzer/restapp#4]
So this:

`container.ioc(ConnectionManager.class, new SingletonFactory(cm));`

can be simplified to:

`container.ioc(ConnectionManager.class, cm);`

if `ConnectionManager` implements `Factory`.

Just an idea...

At least we should have a helper method `singleton(cm)` in MentaContainer that translates to `new SingletonFactory(cm)`.

**Comment by saoj** [comment]
Thinking better... ConnectionManager should probably be a factory of `Connection`s, not a factory of itself (singleton factory). That way we would be able to perhaps get rid of the `ConnectionFactory` class?

**Comment by klutzer** [comment]
Very interesting, but actually the ConnectionManager instance is mapped as a singleton while the ConnectionFactory has to be thread scoped. So what do you suggest?
