### ISSUE TITLE
IoC for DAO looks weird

### ISSUE THREAD

**Issue by saoj** [klutzer/restapp#8]
`private DummyBeanDAO dummyDAO = App.container().get(DummyBeanDAO.class);`

This looks weird. It is not much different than a `new DummyBeanDAO` although I understand that the container is doing the wiring. The `construct` or `inject` from `Container.java` is probably what we want here. That would also make the line below unnecessary in the configuration:

`container.ioc(DummyBeanDAO.class);`

**Comment by klutzer** [comment]
Already improved with the last MentaContainer version
